### PR TITLE
fix: update Admin redirect after successful registration

### PR DESCRIPTION
**Pull request by Amenu-sh**
## Problem

Admin was not redirected after a successful registration instead it say 404

## Solution

Updated the immediate navigation after successful registration

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Update your .env file and execute 'npm run dev'

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oestrada1001** [comment]
Hi @Amenu-sh,

I tested this locally and it's working fine. The jira ticket states that the user should be redirected to the `/auth/download` page. 

Currently the flow is `/signup-user-complete` -> `/successful` -> `/auth/download`
The flow should actually be `/signup-user-complete` -> `/auth/download`

**Review by oestrada1001 — CHANGES_REQUESTED** [review]
The app is working but the user is being redirect to the `/successful` view instead of the `/auth/download` view as the ticket mentions.

**Review by Amenu-sh — COMMENTED** [review]
fixed and redirecting to auth/download

**Review by oestrada1001 — APPROVED** [review]
Redirects to the correct page. Great job!

**Pull request merged**
